// <auto-generated />
namespace MVC_withCodeLayout_Validation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addAgeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAgeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202406150755051_addAgeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
