// <auto-generated />
namespace WebApplication_CodeFirstApproach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0-preview2-24180-01")]
    public sealed partial class initload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initload));
        
        string IMigrationMetadata.Id
        {
            get { return "202406020653239_init/load"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
