// <auto-generated />
namespace _7.WebApp_Country_State_City.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initLoad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initLoad));
        
        string IMigrationMetadata.Id
        {
            get { return "202407121253297_initLoad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
